### ISSUE TITLE
결과 페이지 구현 - 카카오맵 API

### ISSUE THREAD

**Issue by chonahyeon** [chonahyeon/Capstone-Design-Covid#3]
모델의 예측값을 반환해주는 결과 페이지를 만들어보자.

* [x] 사용자가 선택한 입력 값을 볼 수 있도록 함
* [x] 결과값과 동시에 카카오맵 API를 이용해 약국,병원,편의점 등 카테고리 검색결과를 제공해야함.
* [x]  예측된 병명이 한글이어야함.

**Comment by JEONGDratini** [comment]
korean symptoms applied

**Comment by chonahyeon** [comment]
위의 해당 사항 모두 충족했으므로, 종료합니다.
